
[36m[2023-07-02 23:21:58,576][183185] Environment ant, action_dim=8, obs_dim=87
using cvt archive
no kmeans
[36m[2023-07-02 23:22:02,449][183185] Created Scheduler for cma_maega with an archive learning rate of 0.1, and add mode batch, using solution dim 28816 and archive dims [7, 7, 7, 7, 7, 7]. Min threshold is -500.0. Restart rule is no_improvement
self.next_obs
torch.Size([3000, 87])
tensor([[0.5322, 1.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.5405, 1.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.5269, 1.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.5317, 1.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.5375, 1.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.5420, 1.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       device='cuda:0')
normalize
torch.Size([3000, 87])
step =  0
x.shape
torch.Size([3000, 87])
self.weight
torch.Size([7, 128, 87])
obs per weight
428
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 582, in <module>
    train_ppga(cfg, vec_env)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 398, in train_ppga
    objs, measures, jacobian, metadata = ppo.train(vec_env=vec_env,
  File "/home/icaros/Documents/PPGADev/RL/ppo.py", line 325, in train
    action, logprob, _ = self.vec_inference.get_action(self.next_obs)
  File "/home/icaros/Documents/PPGADev/models/vectorized.py", line 152, in get_action
    action_mean = self.actor_mean(obs)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/icaros/Documents/PPGADev/models/vectorized.py", line 28, in forward
    x = torch.reshape(x, (-1, obs_per_weight, x.shape[1]))
RuntimeError: shape '[-1, 428, 87]' is invalid for input of size 261000
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 582, in <module>
    train_ppga(cfg, vec_env)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 398, in train_ppga
    objs, measures, jacobian, metadata = ppo.train(vec_env=vec_env,
  File "/home/icaros/Documents/PPGADev/RL/ppo.py", line 325, in train
    action, logprob, _ = self.vec_inference.get_action(self.next_obs)
  File "/home/icaros/Documents/PPGADev/models/vectorized.py", line 152, in get_action
    action_mean = self.actor_mean(obs)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/icaros/Documents/PPGADev/models/vectorized.py", line 28, in forward
    x = torch.reshape(x, (-1, obs_per_weight, x.shape[1]))
RuntimeError: shape '[-1, 428, 87]' is invalid for input of size 261000