
using cvt archive
[36m[2023-06-25 00:56:31,015][126648] Environment ant, action_dim=8, obs_dim=87
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 561, in <module>
    train_ppga(cfg, vec_env)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 334, in train_ppga
    scheduler = create_scheduler(cfg, use_result_archive=use_result_archive)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 232, in create_scheduler
    ckdtree_kwargs=cfg.cvt_ckdtree)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/attrdict/mixins.py", line 80, in __getattr__
    raise AttributeError(
AttributeError: 'AttrDict' instance has no attribute 'cvt_ckdtree'
Traceback (most recent call last):
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 561, in <module>
    train_ppga(cfg, vec_env)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 334, in train_ppga
    scheduler = create_scheduler(cfg, use_result_archive=use_result_archive)
  File "/home/icaros/Documents/PPGADev/algorithm/train_ppga.py", line 232, in create_scheduler
    ckdtree_kwargs=cfg.cvt_ckdtree)
  File "/home/icaros/anaconda3/envs/ppga/lib/python3.9/site-packages/attrdict/mixins.py", line 80, in __getattr__
    raise AttributeError(
AttributeError: 'AttrDict' instance has no attribute 'cvt_ckdtree'